language: node_js

node_js:
  - "7.7"

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - git config --global user.name 'whatwewant'
  - git config --global user.email 'tobewhatwewant@gmail.com'
  - git clone --branch gh-pages https://${GH_REF} gh-pages

script:
  - npm test

after_success:
  - npm run build
  - cp -rf dist/* gh-pages
  - cd gh-pages
  - git add --all .
  - git commit -a -m ':sparkles:(TravisCI) automatically update from travis_ci'
  - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
  global:
    - GH_REF: github.com/whatwewant/play-music.git
